<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>POS — Caseer System</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900">
<header class="border-b bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div><p class="text-sm font-semibold text-indigo-600">CASEER SYSTEM</p><h1 class="text-xl font-bold">Point of Sale</h1></div><a href="{{ route('dashboard') }}" class="rounded-lg border px-4 py-2 text-sm">Dashboard</a></div></header>
<main class="mx-auto max-w-7xl px-6 py-6">
@if(session('error'))<div class="mb-4 rounded-lg bg-red-50 p-4 text-red-700">{{ session('error') }}</div>@endif
<form method="POST" action="{{ route('sales.checkout') }}" id="checkout-form">@csrf
<div class="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
<section class="rounded-2xl bg-white p-5 shadow-sm">
<div class="flex flex-col gap-3 sm:flex-row sm:items-end"><div class="flex-1"><label class="text-sm font-medium">Cari SKU / Barcode / Nama</label><input id="search" autofocus class="mt-1 w-full rounded-lg border px-3 py-2" placeholder="Scan barcode atau ketik nama..."></div><div class="w-full sm:w-64"><label class="text-sm font-medium">Store</label><select name="store_id" id="store_id" class="mt-1 w-full rounded-lg border px-3 py-2" @if($stores->count()===1) disabled @endif>@foreach($stores as $candidate)<option value="{{ $candidate->id }}" @selected($candidate->id===$store->id)>{{ $candidate->name }}</option>@endforeach</select>@if($stores->count()===1)<input type="hidden" name="store_id" value="{{ $store->id }}">@endif</div></div>
<div id="results" class="mt-4 grid gap-2 sm:grid-cols-2"></div>
<div class="mt-6 overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="border-b text-left text-slate-500"><th class="px-2 py-3">Produk</th><th class="px-2 py-3">Harga</th><th class="px-2 py-3 w-28">Qty</th><th class="px-2 py-3">Diskon</th><th class="px-2 py-3">Pajak</th><th class="px-2 py-3 text-right">Total</th><th></th></tr></thead><tbody id="cart"></tbody></table></div>
</section>
<section class="rounded-2xl bg-white p-5 shadow-sm"><h2 class="text-lg font-bold">Pembayaran</h2><div class="mt-4 space-y-4"><div><label class="text-sm font-medium">Metode</label><select name="payment_method" id="payment_method" class="mt-1 w-full rounded-lg border px-3 py-2"><option value="cash">Tunai</option><option value="card">Kartu</option><option value="qris">QRIS</option><option value="transfer">Transfer</option></select></div><div><label class="text-sm font-medium">Dibayar</label><input type="number" step="0.01" min="0" name="paid_amount" id="paid_amount" class="mt-1 w-full rounded-lg border px-3 py-2" required></div><div><label class="text-sm font-medium">Referensi Pembayaran</label><input name="payment_reference" id="payment_reference" class="mt-1 w-full rounded-lg border px-3 py-2" placeholder="Opsional untuk non-tunai"></div><div><label class="text-sm font-medium">Catatan</label><textarea name="notes" class="mt-1 w-full rounded-lg border px-3 py-2" rows="2"></textarea></div></div>
<div class="mt-6 space-y-2 border-t pt-4"><div class="flex justify-between"><span>Subtotal</span><strong id="subtotal">Rp0</strong></div><div class="flex justify-between"><span>Diskon item</span><strong id="discount">Rp0</strong></div><div class="flex justify-between"><span>Pajak item</span><strong id="tax">Rp0</strong></div><div class="flex justify-between text-lg"><span>Total</span><strong id="grand">Rp0</strong></div><div class="flex justify-between text-emerald-700"><span>Kembalian</span><strong id="change">Rp0</strong></div></div>
<input type="hidden" name="items" id="items-json"><input type="hidden" name="discount_total" id="discount_total"><input type="hidden" name="tax_total" id="tax_total">
<button id="submit" class="mt-6 w-full rounded-xl bg-indigo-600 px-4 py-3 font-semibold text-white hover:bg-indigo-700">Bayar & Selesaikan Transaksi</button>
</section></div></form></main>
<script>
const state={items:[],products:[]};
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
const store=()=>document.getElementById('store_id').value;
async function search(){const q=document.getElementById('search').value.trim();if(!q)return;const r=await fetch(`{{ route('sales.products') }}?store_id=${store()}&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}});if(!r.ok)return;state.products=await r.json();document.getElementById('results').innerHTML=state.products.map(p=>`<button type="button" onclick="add(${p.id})" class="rounded-xl border p-3 text-left hover:border-indigo-400 hover:bg-indigo-50"><span class="font-semibold">${p.name}</span><span class="block text-xs text-slate-500">${p.sku} · ${p.barcode||'-'} · ${p.stock===null?'Non-stock':'Stok '+p.stock}</span><span class="mt-1 block font-medium">${money(p.selling_price)}</span></button>`).join('');}
document.getElementById('search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search();}});document.getElementById('search').addEventListener('input',()=>{clearTimeout(window.timer);window.timer=setTimeout(search,250)});
document.getElementById('store_id').addEventListener('change',()=>{state.items=[];render();});
function add(id){const p=state.products.find(x=>x.id===id);if(!p)return;const existing=state.items.find(x=>x.product_id===id);if(existing)existing.quantity+=1;else state.items.push({product_id:p.id,name:p.name,price:p.selling_price,stock:p.stock,track_stock:p.track_stock,quantity:1,discount:0,tax:0});render();document.getElementById('search').select();}
function remove(i){state.items.splice(i,1);render();}
function render(){const cart=document.getElementById('cart');cart.innerHTML=state.items.map((x,i)=>{const base=x.price*x.quantity;return `<tr class="border-b"><td class="px-2 py-3"><div class="font-medium">${x.name}</div><div class="text-xs text-slate-500">${x.track_stock?'Stok '+x.stock:'Non-stock'}</div><input type="hidden" name="items[${i}][product_id]" value="${x.product_id}"></td><td class="px-2 py-3">${money(x.price)}</td><td class="px-2 py-3"><input class="w-24 rounded border px-2 py-1" type="number" min="0.001" step="0.001" name="items[${i}][quantity]" value="${x.quantity}" onchange="setVal(${i},'quantity',this.value)"></td><td class="px-2 py-3"><input class="w-24 rounded border px-2 py-1" type="number" min="0" step="0.01" name="items[${i}][discount]" value="${x.discount}" onchange="setVal(${i},'discount',this.value)"></td><td class="px-2 py-3"><input class="w-24 rounded border px-2 py-1" type="number" min="0" step="0.01" name="items[${i}][tax]" value="${x.tax}" onchange="setVal(${i},'tax',this.value)"></td><td class="px-2 py-3 text-right font-semibold">${money(Math.max(0,base-x.discount+x.tax))}</td><td><button type="button" onclick="remove(${i})" class="text-red-600">Hapus</button></td></tr>`}).join('');
let sub=0,disc=0,tax=0;state.items.forEach(x=>{sub+=x.price*x.quantity;disc+=+x.discount;tax+=+x.tax});const grand=Math.max(0,sub-disc+tax);document.getElementById('subtotal').textContent=money(sub);document.getElementById('discount').textContent=money(disc);document.getElementById('tax').textContent=money(tax);document.getElementById('grand').textContent=money(grand);document.getElementById('discount_total').value=0;document.getElementById('tax_total').value=0;const paid=+(document.getElementById('paid_amount').value||0);document.getElementById('change').textContent=money(Math.max(0,paid-grand));document.getElementById('items-json').value=JSON.stringify(state.items.map(x=>({product_id:x.product_id,quantity:x.quantity,discount:x.discount,tax:x.tax})));}
function setVal(i,k,v){state.items[i][k]=+v;render();}
document.getElementById('paid_amount').addEventListener('input',render);document.getElementById('payment_method').addEventListener('change',render);document.getElementById('checkout-form').addEventListener('submit',e=>{if(!state.items.length){e.preventDefault();alert('Tambahkan minimal satu produk.');return;}const paid=+(document.getElementById('paid_amount').value||0);const grand=[...document.querySelectorAll('#cart tr')].length;});render();
</script></body></html>
