@extends('layouts.app')
@section('content')
<div class="max-w-7xl mx-auto px-4 py-8">
    <div class="flex justify-between items-center mb-6"><div><h1 class="text-2xl font-bold">User Management</h1><p class="text-gray-500">Kelola akun, role, store, dan status pengguna.</p></div><a href="{{ route('admin.users.create') }}" class="px-4 py-2 rounded bg-gray-900 text-white">Tambah User</a></div>
    @if(session('success'))<div class="mb-4 rounded bg-green-100 p-3 text-green-800">{{ session('success') }}</div>@endif
    <form class="grid md:grid-cols-4 gap-3 mb-5"><input name="search" value="{{ request('search') }}" placeholder="Cari nama/email" class="border rounded px-3 py-2"><select name="role" class="border rounded px-3 py-2"><option value="">Semua role</option>@foreach(['super_admin','owner','manager','cashier','inventory_staff'] as $role)<option value="{{ $role }}" @selected(request('role') === $role)>{{ $role }}</option>@endforeach</select><select name="active" class="border rounded px-3 py-2"><option value="">Semua status</option><option value="1" @selected(request('active') === '1')>Aktif</option><option value="0" @selected(request('active') === '0')>Nonaktif</option></select><button class="rounded bg-gray-200 px-4 py-2">Filter</button></form>
    <div class="overflow-x-auto bg-white rounded shadow"><table class="w-full text-sm"><thead class="bg-gray-50"><tr><th class="p-3 text-left">Nama</th><th class="p-3 text-left">Email</th><th class="p-3 text-left">Role</th><th class="p-3 text-left">Store</th><th class="p-3 text-left">Status</th><th class="p-3"></th></tr></thead><tbody>@foreach($users as $user)<tr class="border-t"><td class="p-3">{{ $user->name }}</td><td class="p-3">{{ $user->email }}</td><td class="p-3">{{ $user->role }}</td><td class="p-3">{{ $user->store?->name ?? 'Global' }}</td><td class="p-3">{{ $user->is_active ? 'Aktif' : 'Nonaktif' }}</td><td class="p-3 text-right"><a class="underline mr-3" href="{{ route('admin.users.edit', $user) }}">Edit</a>@if($user->is_active && auth()->id() !== $user->id)<form class="inline" method="POST" action="{{ route('admin.users.destroy', $user) }}">@csrf @method('DELETE')<button onclick="return confirm('Nonaktifkan user ini?')" class="text-red-600">Nonaktifkan</button></form>@endif</td></tr>@endforeach</tbody></table></div>{{ $users->links() }}
</div>
@endsection
