<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inventory - Caseer System</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
<div class="mx-auto max-w-7xl p-6">
    <div class="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-2xl font-bold">Inventory</h1><p class="text-sm text-slate-500">{{ $store->name }} · {{ $lowStockCount }} produk di bawah minimum</p></div><div class="flex gap-2"><a class="rounded bg-slate-800 px-4 py-2 text-sm text-white" href="{{ route('dashboard') }}">Dashboard</a><a class="rounded border bg-white px-4 py-2 text-sm" href="{{ route('inventory.movements', ['store_id'=>$store->id]) }}">Ledger</a></div></div>
    @if(session('success'))<div class="mb-4 rounded border border-green-200 bg-green-50 p-3 text-green-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mb-4 rounded border border-red-200 bg-red-50 p-3 text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="mb-4 flex flex-wrap gap-2">
        @foreach(['receive'=>'Stock In','issue'=>'Stock Out','adjust'=>'Adjustment','opname'=>'Stock Opname','transfer'=>'Transfer'] as $key=>$label)<a class="rounded bg-white px-4 py-2 text-sm shadow-sm ring-1 ring-slate-200 hover:bg-slate-100" href="{{ route('inventory.create',$key) }}">{{ $label }}</a>@endforeach
    </div>
    <form class="mb-5 flex flex-wrap gap-2" method="get"><select name="store_id" class="rounded border p-2">@foreach($stores as $item)<option value="{{ $item->id }}" @selected($item->id === $store->id)>{{ $item->name }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" class="rounded border p-2" placeholder="SKU, barcode, nama..."><label class="flex items-center gap-2 rounded border bg-white px-3"><input type="checkbox" name="low_stock" value="1" @checked(request('low_stock'))> Low stock</label><button class="rounded bg-indigo-600 px-4 py-2 text-white">Filter</button></form>
    <div class="overflow-x-auto rounded-lg bg-white shadow-sm ring-1 ring-slate-200"><table class="min-w-full text-sm"><thead class="bg-slate-100"><tr><th class="p-3 text-left">SKU</th><th class="p-3 text-left">Produk</th><th class="p-3 text-right">Stok</th><th class="p-3 text-right">Reserved</th><th class="p-3 text-right">Minimum</th><th class="p-3 text-left">Status</th></tr></thead><tbody>@forelse($inventories as $inventory)<tr class="border-t"><td class="p-3">{{ $inventory->product->sku }}</td><td class="p-3">{{ $inventory->product->name }}</td><td class="p-3 text-right font-semibold">{{ number_format((float)$inventory->quantity,3) }}</td><td class="p-3 text-right">{{ number_format((float)$inventory->reserved_quantity,3) }}</td><td class="p-3 text-right">{{ number_format((float)$inventory->product->minimum_stock,3) }}</td><td class="p-3">@if((float)$inventory->quantity <= (float)$inventory->product->minimum_stock)<span class="rounded bg-red-100 px-2 py-1 text-red-700">Low stock</span>@else<span class="rounded bg-green-100 px-2 py-1 text-green-700">Normal</span>@endif</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Belum ada saldo inventory.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-4">{{ $inventories->links() }}</div>
</div></body></html>
