<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $saleReturn->return_number }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900">
<div class="mx-auto max-w-5xl p-6">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('sale-returns.index') }}" class="text-sm text-indigo-600">← Riwayat Retur</a><h1 class="mt-2 text-2xl font-bold">{{ $saleReturn->return_number }}</h1><p class="text-slate-500">Invoice {{ $saleReturn->sale->invoice_number }}</p></div><button onclick="window.print()" class="rounded-lg bg-slate-900 px-4 py-2 text-white print:hidden">Cetak</button></div>
    <div class="mt-6 grid gap-4 md:grid-cols-3"><div class="rounded-xl bg-white p-4 shadow-sm"><div class="text-xs text-slate-500">Toko</div><div class="font-semibold">{{ $saleReturn->store->name }}</div></div><div class="rounded-xl bg-white p-4 shadow-sm"><div class="text-xs text-slate-500">Tanggal</div><div class="font-semibold">{{ $saleReturn->returned_at->format('d/m/Y H:i') }}</div></div><div class="rounded-xl bg-white p-4 shadow-sm"><div class="text-xs text-slate-500">Diproses oleh</div><div class="font-semibold">{{ $saleReturn->processor->name }}</div></div></div>
    <div class="mt-4 overflow-x-auto rounded-xl bg-white shadow-sm"><table class="min-w-full text-sm"><thead class="border-b bg-slate-50 text-left"><tr><th class="p-3">Produk</th><th class="p-3">Qty</th><th class="p-3">Refund/Unit</th><th class="p-3">Refund</th><th class="p-3">Restock</th></tr></thead><tbody class="divide-y">@foreach($saleReturn->items as $item)<tr><td class="p-3">{{ $item->saleItem->product->name }}</td><td class="p-3">{{ number_format((float)$item->quantity,3,',','.') }}</td><td class="p-3">Rp {{ number_format((float)$item->refund_unit_price,2,',','.') }}</td><td class="p-3">Rp {{ number_format((float)$item->refund_total,2,',','.') }}</td><td class="p-3">{{ $item->restock ? 'Ya' : 'Tidak' }}</td></tr>@endforeach</tbody></table></div>
    <div class="mt-4 rounded-xl bg-white p-4 shadow-sm"><div class="flex justify-between"><span>Alasan</span><span>{{ $saleReturn->reason ?: '-' }}</span></div><div class="mt-3 flex justify-between border-t pt-3 text-lg font-bold"><span>Total Refund</span><span>Rp {{ number_format((float)$saleReturn->refund_total,2,',','.') }}</span></div></div>
</div></body></html>
